### ISSUE TITLE
Compatibility with NestJS version 7

### ISSUE THREAD

**Issue by ikarusnc** [bmstefanski/nestjs-shell#1]
Issue type:

question
bug report
feature request

documentation issue

nestjs-shell version
1.0.7

[Nest CLI]
Nest CLI Version : 7.5.1 

[Nest Platform Information]
platform-express version : 7.4.4
sequelize version        : 0.1.1
common version           : 7.4.4
core version             : 7.4.4

Excepted behavior

no warning message when install nestjs-shell
Actual behavior or outcome (for issue)

npm WARN nestjs-shell@1.0.7 requires a peer of @nestjs/common@^6.7.2 but none is installed. You must install peer dependencies yourself.
npm WARN nestjs-shell@1.0.7 requires a peer of @nestjs/core@^6.7.2 but none is installed. You must install peer dependencies yourself.

When I install nestjs-config npm i nestjs-shell I get a npm warning message as I mentioned above. Are there any plans to upgrade the lib for compatibility with NestJS version 7 ?

**Comment by bmstefanski** [comment]
@ikarusnc, I am sorry I did not get a notification about the issue! :(
I don't know if you still need it, but gonna bump the nest version this afternoon.

**Comment by bmstefanski** [comment]
Should be fixed in version `1.1.0`
