### ISSUE TITLE
Add missing `ShellModule` import to `README.md` usage sample

### ISSUE THREAD

**Issue by micalevisk** [bmstefanski/nestjs-shell#9]
https://github.com/bmstefanski/nestjs-shell/blob/0a8c769624da6b10ddb9502a15fc937d7615bd9f/README.md#L54-L57

Above you're using `ShellModule` but forgot to import it in L54 :p

**Comment by bmstefanski** [comment]
Hi!!! Thanks for seeing this - fixed!
